version: "3.7"

services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 33060:3306
    volumes:
      - ./docker-compose-data/mysql:/var/lib/mysql
  server:
    build: ./server
    command: ./node_modules/.bin/nodemon index.js
    environment:
      DATABASE_URL: mysql2://root:root@mysql:3306/ads
      PORT: 3001
    links:
      - mysql
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
  client:
    build: ./client
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
